### ISSUE TITLE
upgrade libphp to 7.4 to fix error when connecting to mysql 8

### ISSUE THREAD

**Issue by benwbooth** [bitnami/bitnami-docker-phpmyadmin#24]
Mysql 8 changed the default authentication to `caching_sha2_password`. PHP versions less than 7.4 do not support connecting to mysql via this authentication method. Upgrading libphp to >= 7.4 would fix this problem. It's currently impossible to connect to mysql 8 using this Dockerfile.

**Comment by juan131** [comment]
Hi @benwbooth 

Thanks so much for reporting this issue!! I was able to reproduce it using the Docker Compose below:

```yaml
version: '2'
services:
  mysql:
    image: 'docker.io/bitnami/mysql:8.0-debian-10'
    environment:
      - MYSQL_ROOT_PASSWORD=bitnami
    volumes:
      - 'mysql_data:/bitnami'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
```

I have created an internal task to upgrade libphp to 7.4 on this Docker image. We'll keep you updated about our progress.

Thanks again for reporting it.
