### ISSUE TITLE
docker and bitnami/phppgadmin: How to connect to the remote postgresql database

### ISSUE THREAD

**Issue by sant527** [bitnami/bitnami-docker-phpmyadmin#32]
I am trying to connect to a remote postgresql database using the `bitnami/phppgadmin` docker

How to mention the host name

```
  phppgadmin:
    image: "bitnami/phppgadmin:7.13.0"
    ports:
      - "8080:8080"
      - '443:8443'
    environment:
      PHP_PG_ADMIN_SERVER_HOST: 'xx.xx.xx.xx'
      PHP_PG_ADMIN_SERVER_PORT: 5432
```

I am trying this, but i am not able to login in the dash board.

I have set the env variables based on the `dockage/phppgadmin`. BUt bitnami has no such `options`

I will accessing the phppgadmin from my localhost only
