### ISSUE TITLE
Container does not work on M1 arch

### ISSUE THREAD

**Issue by PiotrCzapla** [bitnami/bitnami-docker-phpmyadmin#33]
If you run the phpmyadmin in docker on M1, the container crashes with 
' [core:emerg] [pid 122] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex '

here is an example docker-compomse.yaml
```
version: '3'
services:
    mysql1:
        image: mariadb:10.5.9
    phpmyadmin:
        image: bitnami/phpmyadmin:5.0.2-debian-10-r72
        ports:
            - 8080:80
            - 8443:443
```

Below are the logs of the contianer
```
phpmyadmin_1  | nami    INFO  Initializing php
phpmyadmin_1  | nami    INFO  php successfully initialized
phpmyadmin_1  | nami    INFO  Initializing apache
phpmyadmin_1  | nami    INFO  apache successfully initialized
phpmyadmin_1  | nami    INFO  Initializing phpmyadmin
phpmyadmin_1  | phpmyad INFO  Preparing PHP environment...
phpmyadmin_1  | phpmyad INFO  Preparing Apache environment...
phpmyadmin_1  | phpmyad INFO  Configuring App
phpmyadmin_1  | phpmyad INFO  Generating blowfish_ecret
phpmyadmin_1  | nami    INFO  phpmyadmin successfully initialized
phpmyadmin_1  | INFO  ==> Starting gosu... 
phpmyadmin_1  | [Tue May 11 11:47:52.493235 2021] [core:emerg] [pid 122] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex 
phpmyadmin_1  | (95)Operation not supported: could not create accept mutex
phpmyadmin_1  | AH00015: Unable to open logs
replication_phpmyadmin_1 exited with code 1
```
